// you have to generate a new uuid for every request made.
// make use of uuid frameworks to generate this.

// to register as a new user on the platform, you need to create a uuid and store this somewhere for future use as  username in the auth header. Then you will get a key both of which you will use indefinitely. Password is y

// the API key is your password to making all requests
// the username is that reference id created using a uuid framework.

// The api key times out and you 

// username is your reference id which you generated with the uuid framework.

// REQUEST HEADERS.
// ================
// 1. X-Reference-Id - this is generated by the uuid framework
// 2. X-Callback-Url - URL to the server where the callback should be sent. This should be reachable
// 3. X-Target-Environment - "sandbox"
// 4. Content-Type - application/json
// 5. Ocp-Apim-Subscription-Key - subscription key in your profile on the mtn momopay.

// =========================================================
// !!!!!!!!!!!!!!!!!!!!!!! IMPORTANT !!!!!!!!!!!!!!!!!!!!!!!
// =========================================================

// X-REFERENCE-ID : 6c6b0753-4a94-4baf-823c-f5c9220575a3
// API_KEY : b0b11d0fe14041279bc0c044de07345b